### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by Junichiro178** [Baek830/fleamarket_sample_77a#35]
■ URL
IPアドレス：http://54.95.142.131/
Github（最終課題のリポジトリ）：https://github.com/Baek830/fleamarket_sample_77a

■ Basic認証
ID：admin
Pass：77aa

■ テスト用アカウント
◯ 購入者用
メールアドレス：buyer@gmail.com
パスワード：aaaaaaaa

◯ 購入用カード情報
番号：4242424242424242
期限：12/22
セキュリティカード：123

◯ 出品者用
メールアドレス：seller@gmail.com
パスワード：bbbbbbbb

**Comment by Junichiro178** [comment]
> 77期aチームさん、早速のご提出ありがとうございます！
> 挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！
> 
> [修正箇所]
> [**商品購入時**]
> `購入が完了したら購入完了ページ、またはトップページに遷移する`
> こちら、現在購入完了後は商品詳細ページへ戻る仕様になっております。上記どちらかに修正をお願いいたします。
> 
> **その他**
> `出品内容・販売価格が適切である（公序良俗・著作権に反する画像を使用したり、不適切な文言を使用していない）`
> ご投稿頂いている商品は、フリー素材またはご自身で撮影された画像を使用されていますか？
> 販売価格もあわせて今一度ご確認をお願いいたします。
> 
> 以上修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
> https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

### 修正点
・商品購入後の遷移先をトップページに変更しました
・登録商品を整理し、著作権確認を行った商品のみを取り扱う状態としました

**Comment by kubota-tec** [comment]
77期aチームさん、修正ありがとうございます！
挙動確認させて頂いたところ、1点不備が見受けられましたので修正をお願いします！

[修正箇所]
**その他**
`すくなくとも3以上の商品を投稿している`

こちら、お手数ですが追加でサンプル商品`＜出品内容・販売価格が適切である（公序良俗・著作権に反する画像を使用したり、不適切な文言を使用していない）＞`の投稿を3点以上お願いいたします。

以上修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by Baek830** [comment]
3つ商品を投稿しましたので、ご確認お願いします。

**Comment by kubota-tec** [comment]
77期aチームさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。
